### ISSUE TITLE
ERRO[0000] Invalid value for poll interval parameter: time: invalid duration "" 

### ISSUE THREAD

**Issue by kiranashav** [ibm-messaging/mq-metric-samples#256]
Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.
[mqm@localhost mq_prometheus]$ sudo docker run -p 9157:9157 -v /home/mqm/src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus:/opt/config -it --rm mqprom:2.0
[sudo] password for mqm: 
IBM MQ metrics exporter for Prometheus monitoring
MQ Go Version : v5.5.0

ERRO[0000] Invalid value for poll interval parameter: time: invalid duration "" 
INFO[0000] Done.                                        
[mqm@localhost mq_prometheus]$ 
Not sure where to fix the Invalid duration poll Interval parameter
===============================
Prometheus.yaml file 

[mqm@localhost mq_prometheus]$ cat mq_prometheus.yaml 
```
# my global config
global:
  scrape_interval:     15s # Scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any time series scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  # Adding a reference to an MQ monitor. All we have to do is
  # name the host and port on which the monitor is listening.
  # Port 9157 is the reserved default port for this monitor.
  - job_name: 'ibmmq'
    scrape_interval: 15s

    static_configs:
       - targets: ['localhost:9157']
  # targets: ['hostname.example.com:9157','hostname.example.com:9158'] is
  # the syntax if you want to have several prometheus monitors on the same
  # box.

```
