### ISSUE TITLE
Ways to support all Queue Handle query?

### ISSUE THREAD

**Issue by rex657** [ibm-messaging/mq-metric-samples#323]
I am using mq_json exporter with objects config as below, I am able to get the queue metrics like inputHandles and outputHandles:
```
objects:
    queues:
    - "*"
    channels:
    - "!SYSTEM.*"
    topics:
    - "Test_Topic"
    subscriptions:
    - "*"
```
Is there any way for the agent to export the queue handle details as part of the Queue status? I checked both queue.go and usage.go, the queue.go doesn't seem to call out for Handle type metrics and usage.go is for z/OS bufferpool use query.

Any advice is appreciated
