### ISSUE TITLE
Adding Docker support for prometheus to make easier adoption

### ISSUE THREAD

**Issue by paologallinaharbur** [ibm-messaging/mq-metric-samples#42]
### Use Case

Building and running the exporter can be difficult for someone not used to Golang. Moreover having an image for prometheus exporter is becoming a standard.

Related issue https://github.com/ibm-messaging/mq-metric-samples/issues/41

It would be nice to have the possibility to provide a Docker image (Es: `ibm-messaging/prometheus`) with the exporter and the libraries needed.

Environment variables and the config file can be passed at runtime and a docker compose (or kube config file) could help out.

 - Would it be valuable for the users of this exporter?
 - Is there any limitation I am not aware of?
 - Is there any issue with licensing providing the image with those libraries?

If you are interested I could propose a PR, let me know!

---

### Building the image

I performed some tests and for example a Dockerfile as the following would provide a way to spin up the exporter and to configure it:
```Dockerfile
FROM ubuntu:bionic

RUN apt update
RUN apt install -y  curl

RUN  mkdir -p /opt/mqm \
  && chmod a+rx /opt/mqm

ENV RDURL="https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist" \
    RDTAR="IBM-MQC-Redist-LinuxX64.tar.gz" \
    VRMF=9.1.5.0

RUN cd /opt/mqm \
 && curl -LO "$RDURL/$VRMF-$RDTAR" \
 && tar -zxf ./*.tar.gz \
 && rm -f ./*.tar.gz 

COPY ./exporter /exporter

CMD [ "/opt/mqm/exporter" ]
```

This could be the second step of the build dockerfile you have already in place.

A travis job (a manual step, or an other CI) could for example push the image to the repository and the user would need only to run:

```
$docker run -e MQSERVER=CHAEL1/TCP/'<IP>(<PORT>)'  -v $(pwd)/mq_prometheus.yaml:/mq_prometheus.yaml -it ibm-messaging/prometheus:latest /exporter -f /mq_prometheus.yaml
```

---

### Leveraging the image

Having a docker image could open some interesting paths and helping the configuration phase, for example running it in a docker compose together with a prometheus scraper.

It would scrape and forward metrics to a backend after processing them (for example  I tested out a solution using https://github.com/newrelic/nri-prometheus)

``` yaml
version: '3.0'
services:
  mq-exporter:
    image: ibm-messaging/prometheus:latest
    container_name: mq-exporter
    restart: unless-stopped
    ports:
      - 9171:9171
    volumes:
      - ./mq_prometheus.yml:/mq_prometheus.yaml
    environment:
      - MQSERVER=CHAEL1/TCP/'<IP>(<PORT>)'
  nri-prometheus:
    image: newrelic/nri-prometheus:2.0
    container_name: nri-prometheus
    restart: unless-stopped
    volumes:
      - ./config.yml:/config.yaml
    environment:
      - LICENSE_KEY=<Newrelic license key>
```

**Comment by ibmmqmet** [comment]
By coincidence, this issue arrived in my inbox while I was in the middle of writing/testing something similar. I've now got a sample Dockerfile and script that I'll probably push out at some point when I'm happy with it, but I may make use of your docker-compose example as well. Thanks for raising it. 

I doubt if the people who own our container images would want to make an prebuilt image available (there tends to be a lot of process around publishing such artifacts) but a simple script like this at least ought to make it easier to build and run your own.

**Comment by paologallinaharbur** [comment]
Hello, thanks for the quick reply.

I tested as well a scenario were having the image in the repository was not an option (due to licensing or other issues).
In order to have everything running I was spinning up the Docker Compose compiling the image on the fly with the `build` option, for example:

```yaml
version: '3.1'

services:
  mq-exporter:
    container_name:  mq-exporter
    build:
      context: ../../
      dockerfile: ../Dockerfile
    restart: unless-stopped
    ports:
      - 9171:9171
    volumes:
      - ./mq_prometheus.yml:/mq_prometheus.yaml
    environment:
      - MQSERVER=CHAEL1/TCP/'<IP>(<PORT>)'
  nri-prometheus:
    image: newrelic/nri-prometheus:2.0
    container_name: nri-prometheus
    restart: unless-stopped
    volumes:
      - ./config.yml:/config.yaml
    environment:
      - LICENSE_KEY=<Newrelic license key>
```
The Dockerfile was was a two step ones, taking only the binary and the libraries from the build phase (this phase cannot be skipped since the exporter binaries are not released)

Pushing the image the only requirement was to have docker running and the `compose.yml` file.
However with this approach the only additional requirement is to clone the code and run a script/make calling the `docker compose up` command.
